# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b4d06cac901753f53221ec5b8c647bcd614b59a24a9149b08ce5959c08f868f04e56438ba0eea4905c49cd91efbde9c6f20502308c0cca7d2bc8550b86b9a9

test:
  secret_key_base: c5b3d2e71deb07021b67ae58c7559dfa9333b7014a1bb320ea1f95743ef05fb4f7963e1b62ddc0bd3c42e10ac2080fd3ee5c7a6fd6a8e8d19a5b761d72f68d14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
